#!/usr/bin/env node
/**
 * Sprint 26 — Legacy state binding audit gate.
 *
 * Wraps `scan.mjs` with a checked-in baseline so the audit is a ratchet, not a
 * snapshot. Running with no arguments compares the live scan against
 * `baseline.json` and exits non-zero when a binding appears that was never
 * audited. Retiring a binding is a clean exit that reminds you to refresh the
 * baseline.
 *
 * Usage:
 *   node src/legacy/state/audit.mjs              # gate: fail on unaudited bindings
 *   node src/legacy/state/audit.mjs --update     # refresh baseline.json
 *   node src/legacy/state/audit.mjs --json       # baseline diff as JSON
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { groupByRule, scanRepo } from "./scan.mjs";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const BASELINE_PATH = `${HERE}baseline.json`;

/**
 * Identity of a binding. Deliberately excludes the line number so that
 * unrelated edits above a binding do not invalidate the audit; a new binding or
 * a retired one always does.
 * @param {{ruleId: string, file: string, matched: string}} f
 * @returns {string}
 */
export function signatureOf(f) {
  return `${f.ruleId}::${f.file}::${f.matched}`;
}

/**
 * @param {Array<{ruleId: string, file: string, matched: string}>} findings
 * @param {Array<{ruleId: string, file: string, matched: string}>} baseline
 * @returns {{added: string[], retired: string[]}}
 */
export function diffAgainstBaseline(findings, baseline) {
  const live = new Set(findings.map(signatureOf));
  const known = new Set(baseline.map(signatureOf));
  return {
    added: [...live].filter((s) => !known.has(s)).sort(),
    retired: [...known].filter((s) => !live.has(s)).sort(),
  };
}

function gitHead() {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

function buildBaseline(findings) {
  return {
    $comment:
      "Sprint 26 legacy state binding baseline. Generated by src/legacy/state/audit.mjs --update. Do not edit by hand.",
    generatedAt: new Date().toISOString(),
    gitCommitSha: gitHead(),
    totalFindings: findings.length,
    byRule: Object.fromEntries(
      groupByRule(findings).map((g) => [g.ruleId, g.count]),
    ),
    findings: findings.map((f) => ({
      ruleId: f.ruleId,
      file: f.file,
      line: f.line,
      matched: f.matched,
    })),
  };
}

/**
 * @returns {string} absolute path to the checked-in baseline
 */
export function baselinePath() {
  return BASELINE_PATH;
}

/**
 * @returns {{gitCommitSha: string, totalFindings: number, findings: object[]}}
 */
export function readBaseline() {
  return JSON.parse(readFileSync(BASELINE_PATH, "utf8"));
}

const invokedDirectly =
  process.argv[1] &&
  (() => {
    try {
      return fileURLToPath(import.meta.url) === process.argv[1];
    } catch {
      return false;
    }
  })();

if (invokedDirectly) {
  const args = process.argv.slice(2);
  const findings = scanRepo();

  if (args.includes("--update")) {
    writeFileSync(
      BASELINE_PATH,
      JSON.stringify(buildBaseline(findings), null, 2) + "\n",
      "utf8",
    );
    process.stdout.write(
      `Baseline updated: ${findings.length} findings → ${BASELINE_PATH}\n`,
    );
    process.exit(0);
  }

  const baseline = readBaseline();
  const { added, retired } = diffAgainstBaseline(findings, baseline.findings ?? []);

  if (args.includes("--json")) {
    process.stdout.write(
      JSON.stringify(
        {
          baselineCommit: baseline.gitCommitSha,
          baselineTotal: baseline.totalFindings,
          liveTotal: findings.length,
          added,
          retired,
        },
        null,
        2,
      ) + "\n",
    );
  }

  if (added.length === 0 && retired.length === 0) {
    process.stdout.write(
      `✓ Legacy state bindings match baseline (${findings.length} findings, ` +
        `baseline @ ${baseline.gitCommitSha}).\n`,
    );
    process.exit(0);
  }

  if (added.length > 0) {
    process.stderr.write(
      `✗ ${added.length} unaudited legacy state binding(s):\n` +
        added.map((s) => `    + ${s}`).join("\n") +
        "\n  Audit each one and refresh with: node src/legacy/state/audit.mjs --update\n",
    );
  }
  if (retired.length > 0) {
    process.stdout.write(
      `✓ ${retired.length} baseline binding(s) no longer present (retired):\n` +
        retired.map((s) => `    - ${s}`).join("\n") +
        "\n  Refresh with: node src/legacy/state/audit.mjs --update\n",
    );
  }

  // Added bindings are the failure mode; retirements are progress.
  process.exit(added.length > 0 ? 1 : 0);
}
